### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by ruffsl**
What license would we like to use? Same as Kimera-VIO-ROS (1)?
https://choosealicense.com/licenses/bsd-2-clause/

### CODE REVIEW

**Comment by lucacarlone** [comment]
I would go for MIT license (pretty much the same as BSD) - it is one of the most permissive

**Comment by ToniRV** [comment]
Yes! Thank you!

**Comment by ruffsl** [comment]
@lucacarlone @ToniRV , it seems like one is leaning towards MIT and other is BSD? I merely suggested BSD for consistency or convenance in refactoring code around as maybe later needed with the rest of the kimera ecosystem. Are you planning on migrating the rest of kimera to an MIT licence?

**Comment by lucacarlone** [comment]
same as the rest of Kimera is good! (BSD and MIT are practically the same, so let's stick to the one we have used so far). thanks @ruffsl !

**Review by ToniRV — APPROVED** [review]

**Pull request merged**
